import { ENV } from './env';

// Konfigurasi API
export const API_CONFIG = {
  BASE_URL: ENV.API_BASE_URL,
  ENDPOINTS: {
    AUTH: {
      LOGIN: '/auth/login',
      REFRESH: '/auth/refresh',
      LOGOUT: '/auth/logout',
      ME: '/auth/me',
      UPDATE_PROFILE: '/auth/profile',
      CHANGE_PASSWORD: '/auth/password',
      FORGOT_PASSWORD: '/auth/reset/request',
      RESET_PASSWORD: '/auth/reset/confirm',
      ACTIVATE_ACCOUNT: '/auth/verify/request',
      MICROSOFT_LOGIN: '/auth/microsoft/login',
      MICROSOFT_CALLBACK: '/auth/microsoft/callback',
    },
    USER: {
      PROFILE: '/user/profile',
    },
    PROFILE: {
      UPLOAD_AVATAR: '/profile/avatar',
      DELETE_AVATAR: '/profile/avatar',
      SERVE_AVATAR: (fileName: string) => `/profile/avatar/${fileName}`,
      LECTURER_DATA: '/profile/lecturer-data',
    },
    CPL: {
      BASE: '/cpls',
      BY_ID: (id: string) => `/cpls/${id}`,
      TOGGLE: (id: string) => `/cpls/${id}/toggle`,
      EXPORT_ALL_SCORES: '/cpls/export',
      STUDENTS: (id: string) => `/cpls/${id}/students`,
      STUDENT_OPTIONS: (id: string) => `/cpls/${id}/students/options`,
      STUDENT_BY_ID: (id: string, studentId: string) => `/cpls/${id}/students/${studentId}`,
      STUDENT_IMPORT: (id: string) => `/cpls/${id}/students/import`,
      STUDENT_EXPORT: (id: string) => `/cpls/${id}/students/export`,
    },
    CPMK: {
      BASE: '/cpmks',
      BY_ID: (id: string) => `/cpmks/${id}`,
      COPY_TEMPLATE: '/cpmks/copy-template',
      HIERARCHY: '/cpmks/hierarchy',
    },
    SEMINAR_RUBRIC: {
      CPMKS: '/seminar-rubrics/cpmks',
      CRITERIA: '/seminar-rubrics/criteria',
      CRITERIA_BY_ID: (criteriaId: string) => `/seminar-rubrics/criteria/${criteriaId}`,
      CPMK_CONFIG: (cpmkId: string) => `/seminar-rubrics/cpmk/${cpmkId}`,
      CRITERIA_RUBRICS: (criteriaId: string) => `/seminar-rubrics/criteria/${criteriaId}/rubrics`,
      RUBRIC_BY_ID: (rubricId: string) => `/seminar-rubrics/rubrics/${rubricId}`,
      CRITERIA_REORDER: '/seminar-rubrics/criteria/reorder',
      RUBRICS_REORDER: '/seminar-rubrics/rubrics/reorder',
      WEIGHT_SUMMARY: '/seminar-rubrics/weight-summary',
    },
    DEFENCE_RUBRIC: {
      CPMKS: (role: string) => `/defence-rubrics/cpmks?role=${role}`,
      CRITERIA: '/defence-rubrics/criteria',
      CRITERIA_BY_ID: (criteriaId: string) => `/defence-rubrics/criteria/${criteriaId}`,
      CPMK_CONFIG: (cpmkId: string, role: string) => `/defence-rubrics/cpmk/${cpmkId}?role=${role}`,
      CRITERIA_RUBRICS: (criteriaId: string) => `/defence-rubrics/criteria/${criteriaId}/rubrics`,
      RUBRIC_BY_ID: (rubricId: string) => `/defence-rubrics/rubrics/${rubricId}`,
      CRITERIA_REORDER: '/defence-rubrics/criteria/reorder',
      RUBRICS_REORDER: '/defence-rubrics/rubrics/reorder',
      WEIGHT_SUMMARY: (role: string) => `/defence-rubrics/weight-summary?role=${role}`,
    },
    EXIT_SURVEY: {
      BASE: '/yudisiums/exit-survey',
      BY_ID: (id: string) => `/yudisiums/exit-survey/${id}`,
      TOGGLE: (id: string) => `/yudisiums/exit-survey/${id}/toggle`,
      DUPLICATE: (id: string) => `/yudisiums/exit-survey/${id}/duplicate`,
      QUESTIONS: (formId: string) => `/yudisiums/exit-survey/${formId}/questions`,
      QUESTION_BY_ID: (formId: string, questionId: string) => `/yudisiums/exit-survey/${formId}/questions/${questionId}`,
    },
    YUDISIUM_REQUIREMENTS: {
      BASE: '/yudisiums/yudisium-requirements',
      BY_ID: (id: string) => `/yudisiums/yudisium-requirements/${id}`,
      TOGGLE: (id: string) => `/yudisiums/yudisium-requirements/${id}/toggle`,
      MOVE_TOP: (id: string) => `/yudisiums/yudisium-requirements/${id}/move-top`,
      MOVE_BOTTOM: (id: string) => `/yudisiums/yudisium-requirements/${id}/move-bottom`,
    },
    YUDISIUM_EVENT: {
      BASE: '/yudisiums/event',
      BY_ID: (id: string) => `/yudisiums/event/${id}`,
    },
    YUDISIUM_STUDENT: {
      OVERVIEW: '/yudisiums/student/overview',
      EXIT_SURVEY: '/yudisiums/student/exit-survey',
      EXIT_SURVEY_SUBMIT: '/yudisiums/student/exit-survey/submit',
      REQUIREMENTS: '/yudisiums/student/requirements',
      REQUIREMENTS_UPLOAD: '/yudisiums/student/requirements/upload',
    },
    YUDISIUM_ADMIN: {
      EVENTS: '/yudisiums/admin/events',
      PARTICIPANTS: (yudisiumId: string) => `/yudisiums/admin/${yudisiumId}/participants`,
      PARTICIPANT_DETAIL: (participantId: string) => `/yudisiums/admin/participants/${participantId}`,
      VALIDATE_DOCUMENT: (participantId: string, requirementId: string) =>
        `/yudisiums/admin/participants/${participantId}/requirements/${requirementId}/validate`,
    },
    YUDISIUM_LECTURER: {
      EVENTS: '/yudisiums/lecturer/events',
      PARTICIPANTS: (yudisiumId: string) => `/yudisiums/lecturer/${yudisiumId}/participants`,
      PARTICIPANT_DETAIL: (participantId: string) => `/yudisiums/lecturer/participants/${participantId}`,
      CPL_SCORES: (participantId: string) => `/yudisiums/lecturer/participants/${participantId}/cpl-scores`,
      VERIFY_CPL: (participantId: string, cplId: string) =>
        `/yudisiums/lecturer/participants/${participantId}/cpl/${cplId}/verify`,
      CREATE_CPL_RECOMMENDATION: (participantId: string) =>
        `/yudisiums/lecturer/participants/${participantId}/cpl-recommendation`,
      UPDATE_CPL_RECOMMENDATION_STATUS: (recommendationId: string) =>
        `/yudisiums/lecturer/cpl-recommendation/${recommendationId}/status`,
      DRAFT_SK: (yudisiumId: string) => `/yudisiums/lecturer/${yudisiumId}/draft-sk`,
      UPLOAD_SK: (yudisiumId: string) => `/yudisiums/lecturer/${yudisiumId}/upload-sk`,
    },
    NOTIFICATION: {
      BASE: '/notification',
      UNREAD_COUNT: '/notification/unread-count',
      CHECK_THESIS_DELETED: '/notification/check-thesis-deleted',
      MARK_ALL_READ: '/notification/read-all',
      MARK_READ: (id: string) => `/notification/${id}/read`,
      DELETE: (id: string) => `/notification/${id}`,
      DELETE_ALL: '/notification/all',
      FCM_REGISTER: '/notification/fcm/register',
      FCM_UNREGISTER: '/notification/fcm/unregister',
    },
    THESIS_STUDENT: {
      BASE: '/thesisGuidance/student',
      GUIDANCE_LIST: '/thesisGuidance/student/guidance',
      GUIDANCE_DETAIL: (id: string) => `/thesisGuidance/student/guidance/${id}`,
      GUIDANCE_REQUEST: '/thesisGuidance/student/guidance/request',
      GUIDANCE_RESCHEDULE: (id: string) => `/thesisGuidance/student/guidance/${id}/reschedule`,
      GUIDANCE_CANCEL: (id: string) => `/thesisGuidance/student/guidance/${id}/cancel`,
      GUIDANCE_NOTES: (id: string) => `/thesisGuidance/student/guidance/${id}/notes`,
      PROGRESS: '/thesisGuidance/student/progress',
      PROGRESS_COMPLETE: '/thesisGuidance/student/progress/complete',
      HISTORY: '/thesisGuidance/student/history',
      SUPERVISORS: '/thesisGuidance/student/supervisors',
      SUPERVISOR_AVAILABILITY: (supervisorId: string) => `/thesisGuidance/student/supervisors/${supervisorId}/availability`,
      // Session Summary
      NEEDS_SUMMARY: '/thesisGuidance/student/needs-summary',
      SUBMIT_SUMMARY: (guidanceId: string) => `/thesisGuidance/student/guidance/${guidanceId}/submit-summary`,
      COMPLETE_SESSION: (guidanceId: string) => `/thesisGuidance/student/guidance/${guidanceId}/complete`,
      COMPLETED_HISTORY: '/thesisGuidance/student/completed-history',
      EXPORT_GUIDANCE: (guidanceId: string) => `/thesisGuidance/student/guidance/${guidanceId}/export`,
      GENERATE_LOG: '/thesisGuidance/student/guidance/generate-log',
      // My Thesis
      MY_THESIS: '/thesisGuidance/student/my-thesis',
      UPDATE_THESIS_TITLE: '/thesisGuidance/student/my-thesis/title',
      THESIS_HISTORY: '/thesisGuidance/student/thesis-history',
      PROPOSE_THESIS: '/thesisGuidance/student/propose-thesis',
      // Pembimbing 2 Request
      AVAILABLE_SUPERVISORS_2: '/thesisGuidance/student/available-supervisors-2',
      REQUEST_SUPERVISOR_2: '/thesisGuidance/student/request-supervisor-2',
      PENDING_SUPERVISOR_2: '/thesisGuidance/student/pending-supervisor-2-request',
      CANCEL_SUPERVISOR_2: '/thesisGuidance/student/cancel-supervisor-2-request',
    },
    THESIS_LECTURER: {
      BASE: '/thesisGuidance/lecturer',
      MY_STUDENTS: '/thesisGuidance/lecturer/my-students',
      MY_STUDENTS_DETAIL: (thesisId: string) => `/thesisGuidance/lecturer/my-students/${thesisId}`,
      REQUESTS: '/thesisGuidance/lecturer/requests',
      SCHEDULED: '/thesisGuidance/lecturer/scheduled',
      REQUEST_REJECT: (guidanceId: string) => `/thesisGuidance/lecturer/requests/${guidanceId}/reject`,
      REQUEST_APPROVE: (guidanceId: string) => `/thesisGuidance/lecturer/requests/${guidanceId}/approve`,
      REQUEST_CANCEL: (guidanceId: string) => `/thesisGuidance/lecturer/requests/${guidanceId}/cancel`,
      PROGRESS_SUMMARY: '/thesisGuidance/lecturer/progress',
      PROGRESS_DETAIL: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}`,
      PROGRESS_APPROVE_COMPONENTS: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}/approve`,
      PROGRESS_FINAL_APPROVAL: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}/final-approval`,
      FAIL_THESIS: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}/fail`,
      FEEDBACK: (guidanceId: string) => `/thesisGuidance/lecturer/feedback/${guidanceId}`,
      GUIDANCE_HISTORY: (studentId: string) => `/thesisGuidance/lecturer/guidance-history/${studentId}`,
      SUPERVISOR_ELIGIBILITY: '/thesisGuidance/lecturer/supervisor/eligibility',
      // Session Summary Approval
      PENDING_APPROVAL: '/thesisGuidance/lecturer/pending-approval',
      APPROVE_SUMMARY: (guidanceId: string) => `/thesisGuidance/lecturer/guidance/${guidanceId}/approve-summary`,
      REJECT_SUMMARY: (guidanceId: string) => `/thesisGuidance/lecturer/guidance/${guidanceId}/reject-summary`,
      // Guidance Detail
      GUIDANCE_DETAIL: (guidanceId: string) => `/thesisGuidance/lecturer/guidance/${guidanceId}`,
      // Pembimbing 2 Requests
      SUPERVISOR2_REQUESTS: '/thesisGuidance/lecturer/supervisor2-requests',
      SUPERVISOR2_APPROVE: (requestId: string) => `/thesisGuidance/lecturer/supervisor2-requests/${requestId}/approve`,
      SUPERVISOR2_REJECT: (requestId: string) => `/thesisGuidance/lecturer/supervisor2-requests/${requestId}/reject`,
      APPROVE_THESIS_PROPOSAL: (thesisId: string) => `/thesisGuidance/lecturer/proposals/${thesisId}/approve`,
      TRANSFER_ELIGIBLE_LECTURERS: '/thesisGuidance/lecturer/transfer/eligible-lecturers',
      TRANSFER_REQUEST: '/thesisGuidance/lecturer/transfer/request',
      TRANSFER_INCOMING: '/thesisGuidance/lecturer/transfer/incoming',
      TRANSFER_APPROVE: (notificationId: string) => `/thesisGuidance/lecturer/transfer/${notificationId}/approve`,
      TRANSFER_REJECT: (notificationId: string) => `/thesisGuidance/lecturer/transfer/${notificationId}/reject`,
    },
    THESIS_MONITORING: {
      DASHBOARD: '/thesisGuidance/monitoring/dashboard',
      TRANSFERS_PENDING: '/kadep-transfers/pending',
      TRANSFERS_ALL: '/kadep-transfers/all',
      TRANSFERS_REPORT_DOWNLOAD: '/kadep-transfers/report/download',
      TRANSFER_APPROVE: (notifId: string) => `/kadep-transfers/${notifId}/approve`,
      TRANSFER_REJECT: (notifId: string) => `/kadep-transfers/${notifId}/reject`,
    },
    THESIS_SEMINAR: {
      // --- Shared / Global ---
      BASE: '/thesis-seminars',
      BY_ID: (id: string) => `/thesis-seminars/${id}`,
      OPTIONS_THESES: '/thesis-seminars/options/theses',
      OPTIONS_LECTURERS: '/thesis-seminars/options/lecturers',
      OPTIONS_STUDENTS: '/thesis-seminars/options/students',
      OPTIONS_ROOMS: '/thesis-seminars/options/rooms',
      TEMPLATE: '/thesis-seminars/template',
      EXPORT: '/thesis-seminars/export',
      IMPORT: '/thesis-seminars/import',

      // --- Student Specific ---
      ME_OVERVIEW: '/thesis-seminars/me/overview',
      ME_ATTENDANCE: '/thesis-seminars/me/attendance',
      ME_HISTORY: '/thesis-seminars/me/history',
      ANNOUNCEMENTS: '/thesis-seminars/announcements',

      // --- Lecturer/Kadep Lists ---
      LECTURER_SUPERVISED: '/thesis-seminars?view=supervised_students',
      LECTURER_EXAMINER_REQUESTS: '/thesis-seminars?view=examiner_requests',
      LECTURER_ASSIGNMENT_LIST: '/thesis-seminars?view=assignment',

      // --- Scheduling ---
      SCHEDULING_DATA: (id: string) => `/thesis-seminars/${id}/scheduling-data`,
      SCHEDULE: (id: string) => `/thesis-seminars/${id}/schedule`,

      // --- Documents ---
      DOCUMENT_TYPES: '/thesis-seminars/documents/types',
      DOCUMENTS: (id: string) => `/thesis-seminars/${id}/documents`,
      DOCUMENT_BY_TYPE: (id: string, typeId: string) => `/thesis-seminars/${id}/documents/${typeId}`,
      VALIDATE_DOCUMENT: (id: string, typeId: string) => `/thesis-seminars/${id}/documents/${typeId}/validate`,

      // --- Examiners & Assignment ---
      ELIGIBLE_EXAMINERS: (id: string) => `/thesis-seminars/${id}/eligible-examiners`,
      EXAMINERS: (id: string) => `/thesis-seminars/${id}/examiners`,
      RESPOND_ASSIGNMENT: (id: string, examinerId: string) => `/thesis-seminars/${id}/examiners/${examinerId}/respond`,

      // --- Assessment & Finalization ---
      ASSESSMENT: (id: string) => `/thesis-seminars/${id}/assessment`,
      FINALIZATION_DATA: (id: string) => `/thesis-seminars/${id}/finalization`,
      FINALIZE: (id: string) => `/thesis-seminars/${id}/finalize`,

      // --- Revisions ---
      REVISIONS: (id: string) => `/thesis-seminars/${id}/revisions`,
      REVISION_BY_ID: (id: string, revId: string) => `/thesis-seminars/${id}/revisions/${revId}`,
      APPROVE_REVISION: (id: string, revId: string) => `/thesis-seminars/${id}/revisions/${revId}/approve`,
      UNAPPROVE_REVISION: (id: string, revId: string) => `/thesis-seminars/${id}/revisions/${revId}/unapprove`,
      FINALIZE_REVISIONS: (id: string) => `/thesis-seminars/${id}/revisions/finalize`,

      // --- Audiences ---
      AUDIENCES: (id: string) => `/thesis-seminars/${id}/audiences`,
      AUDIENCE_BY_ID: (id: string, studentId: string) => `/thesis-seminars/${id}/audiences/${studentId}`,
      APPROVE_AUDIENCE: (id: string, studentId: string) => `/thesis-seminars/${id}/audiences/${studentId}/approve`,
      UNAPPROVE_AUDIENCE: (id: string, studentId: string) => `/thesis-seminars/${id}/audiences/${studentId}/unapprove`,
      TOGGLE_AUDIENCE_PRESENCE: (id: string, studentId: string) => `/thesis-seminars/${id}/audiences/${studentId}/presence`,
      AUDIENCES_OPTIONS: (id: string) => `/thesis-seminars/${id}/audiences/options/students`,
      AUDIENCES_TEMPLATE: (id: string) => `/thesis-seminars/${id}/audiences/template`,
      AUDIENCES_EXPORT: (id: string) => `/thesis-seminars/${id}/audiences/export`,
      AUDIENCES_IMPORT: (id: string) => `/thesis-seminars/${id}/audiences/import`,
    },
    THESIS_DEFENCE_STUDENT: {
      OVERVIEW: '/thesis-defences/student/overview',
      DOCUMENT_TYPES: '/thesis-defences/student/documents/types',
      DOCUMENTS: '/thesis-defences/student/documents',
      DOCUMENT_UPLOAD: '/thesis-defences/student/documents/upload',
      REVISIONS: '/thesis-defences/student/revisions',
      HISTORY: '/thesis-defences/student/history',
      DEFENCE_DETAIL: (defenceId: string) => `/thesis-defences/student/defences/${defenceId}`,
      DEFENCE_ASSESSMENT: (defenceId: string) => `/thesis-defences/student/defences/${defenceId}/assessment`,
      DEFENCE_REVISIONS: (defenceId: string) => `/thesis-defences/student/defences/${defenceId}/revisions`,
      CREATE_REVISION: (defenceId: string) => `/thesis-defences/student/defences/${defenceId}/revisions`,
      SAVE_REVISION_ACTION: (revisionId: string) => `/thesis-defences/student/revisions/${revisionId}/action`,
      SUBMIT_REVISION_ACTION: (revisionId: string) => `/thesis-defences/student/revisions/${revisionId}/submit`,
      CANCEL_REVISION_SUBMIT: (revisionId: string) => `/thesis-defences/student/revisions/${revisionId}/cancel-submit`,
      DELETE_REVISION: (revisionId: string) => `/thesis-defences/student/revisions/${revisionId}`,
    },
    THESIS_DEFENCE_ADMIN: {
      LIST: '/thesis-defences/admin',
      DETAIL: (defenceId: string) => `/thesis-defences/admin/${defenceId}`,
      VALIDATE_DOCUMENT: (defenceId: string, documentTypeId: string) =>
        `/thesis-defences/admin/${defenceId}/documents/${documentTypeId}/validate`,
      SCHEDULING_DATA: (defenceId: string) => `/thesis-defences/admin/${defenceId}/scheduling-data`,
      SET_SCHEDULE: (defenceId: string) => `/thesis-defences/admin/${defenceId}/schedule`,
    },
    THESIS_DEFENCE_LECTURER: {
      EXAMINER_REQUESTS: '/thesis-defences/lecturer/examiner-requests',
      SUPERVISED_STUDENTS: '/thesis-defences/lecturer/supervised-students',
      DEFENCE_DETAIL: (defenceId: string) => `/thesis-defences/lecturer/defences/${defenceId}`,
      DEFENCE_ASSESSMENT: (defenceId: string) => `/thesis-defences/lecturer/defences/${defenceId}/assessment`,
      FINALIZATION_DATA: (defenceId: string) => `/thesis-defences/lecturer/defences/${defenceId}/finalization`,
      FINALIZE_DEFENCE: (defenceId: string) => `/thesis-defences/lecturer/defences/${defenceId}/finalize`,
      DEFENCE_REVISIONS: (defenceId: string) => `/thesis-defences/lecturer/defences/${defenceId}/revisions`,
      FINALIZE_REVISIONS: (defenceId: string) => `/thesis-defences/lecturer/defences/${defenceId}/revisions/finalize`,
      APPROVE_REVISION: (defenceId: string, revisionId: string) => `/thesis-defences/lecturer/defences/${defenceId}/revisions/${revisionId}/approve`,
      UNAPPROVE_REVISION: (defenceId: string, revisionId: string) => `/thesis-defences/lecturer/defences/${defenceId}/revisions/${revisionId}/unapprove`,
      RESPOND: (examinerId: string) => `/thesis-defences/lecturer/defences/${examinerId}/respond`,
      ASSIGNMENT_LIST: '/thesis-defences/lecturer/assignment',
      ELIGIBLE_EXAMINERS: (defenceId: string) =>
        `/thesis-defences/lecturer/assignment/${defenceId}/eligible-examiners`,
      ASSIGN_EXAMINERS: (defenceId: string) =>
        `/thesis-defences/lecturer/assignment/${defenceId}`,
    },
    LECTURER_AVAILABILITY: {
      BASE: '/lecturer-availabilities',
      BY_ID: (id: string) => `/lecturer-availabilities/${id}`,
    },
    INTERNSHIP_STUDENT: {
      BASE: '/insternship/registration',
      PROPOSALS: '/insternship/registration/proposals',
      RESPOND_INVITATION: (id: string) => `/insternship/registration/proposals/${id}/respond`,
      COMPANIES: '/insternship/registration/companies',
      ELIGIBLE_STUDENTS: '/insternship/registration/eligible-students',
      SUBMIT_PROPOSAL: '/insternship/registration/submit',
      SUBMIT_COMPANY_RESPONSE: (proposalId: string) => `/insternship/registration/proposals/${proposalId}/company-response`,
      LOGBOOK: '/insternship/activity/logbook',
      UPDATE_LOGBOOK: (id: string) => `/insternship/activity/logbook/${id}`,
      UPDATE_DETAILS: '/insternship/activity/details',
      ACTIVITY: '/insternship/activity',
      REGISTER_SEMINAR: '/insternship/activity/register-seminar',
      UPCOMING_SEMINARS: '/insternship/activity/seminars',
      UPDATE_SEMINAR: (id: string) => `/insternship/activity/seminar/${id}`,
      APPROVE_SEMINAR: (id: string) => `/insternship/activity/guidance/lecturer/seminar/${id}/approve`,
      REJECT_SEMINAR: (id: string) => `/insternship/activity/guidance/lecturer/seminar/${id}/reject`,
      UPLOAD: '/documents/upload',
      VERIFY_FINAL_REPORT: (internshipId: string) => `/insternship/activity/guidance/lecturer/students/${internshipId}/verify-report`,
    },
    INTERNSHIP_OVERVIEW: {
      COMPANIES: '/insternship/overview/companies',
      REPORTS: '/insternship/overview/reports',
      STATS: '/insternship/overview/stats',
    },
    INTERNSHIP_SEKDEP: {
      BASE: '/insternship/sekdep',
      PROPOSALS: '/insternship/sekdep/proposals',
      PROPOSAL_DETAIL: (id: string) => `/insternship/sekdep/proposals/${id}`,
      COMPANY_STATS: '/insternship/sekdep/companies/stats',
      COMPANIES: '/insternship/sekdep/companies',
      COMPANY_DETAIL: (id: string) => `/insternship/sekdep/companies/${id}`,
      COMPANY_RESPONSES: '/insternship/sekdep/company-responses',
      VERIFY_COMPANY_RESPONSE: (id: string) => `/insternship/sekdep/company-responses/${id}/verify`,
      INTERNSHIPS: '/insternship/sekdep/internships',
      INTERNSHIPS_DETAIL: (id: string) => `/insternship/sekdep/internships/${id}`,
      VERIFY_DOCUMENT: (id: string) => `/insternship/sekdep/internships/${id}/verify-document`,
      VERIFY_DOCUMENTS_BULK: (id: string) => `/insternship/sekdep/internships/${id}/verify-documents-bulk`,
      SEND_FIELD_ASSESSMENT: (id: string) => `/insternship/sekdep/internships/${id}/send-field-assessment`,
      LECTURERS_WORKLOAD: '/insternship/sekdep/lecturers/workload',
      LECTURERS_WORKLOAD_EXPORT: '/insternship/sekdep/lecturers/workload/export',
      GUIDANCE_QUESTIONS: '/insternship/sekdep/guidance/questions',
      GUIDANCE_QUESTION_DETAIL: (id: string) => `/insternship/sekdep/guidance/questions/${id}`,
      GUIDANCE_CRITERIA: '/insternship/sekdep/guidance/criteria',
      GUIDANCE_CRITERIA_DETAIL: (id: string) => `/insternship/sekdep/guidance/criteria/${id}`,
      TEMPLATES_GET: (name: string) => `/insternship/sekdep/templates/${name}`,
      TEMPLATES_PREVIEW: (name: string) => `/insternship/sekdep/templates/${name}/preview`,
      TEMPLATES_SAVE: '/insternship/sekdep/templates',
      MONITORING_STATS: '/insternship/monitoring/stats',
      MONITORING_LIST: '/insternship/monitoring/list',
    },
    INTERNSHIP_KADEP: {
      BASE: '/insternship/kadep',
      COMPANY_STATS: '/insternship/kadep/companies/stats',
      COMPANIES: '/insternship/kadep/companies',
      COMPANY_DETAIL: (id: string) => `/insternship/kadep/companies/${id}`,
      PENDING_LETTERS: '/insternship/kadep/pending-letters',
      APPROVE_LETTER: '/insternship/kadep/approve-letter',
    },
    INTERNSHIP_ADMIN: {
      BASE: '/insternship/admin',
      COMPANY_STATS: '/insternship/admin/companies/stats',
      APPROVED_PROPOSALS: '/insternship/admin/proposals/approved',
      APPROVED_PROPOSAL_DETAIL: (id: string) => `/insternship/admin/proposals/${id}`,
      UPDATE_LETTER: (id: string) => `/insternship/admin/proposals/${id}/letter`,
      ASSIGNMENT_PROPOSALS: '/insternship/admin/proposals/assignments',
      ASSIGNMENT_PROPOSAL_DETAIL: (id: string) => `/insternship/admin/proposals/${id}/assignment`,
      UPDATE_ASSIGNMENT_LETTER: (id: string) => `/insternship/admin/proposals/${id}/assignment-letter`,
      VERIFY_COMPANY_RESPONSE: (id: string) => `/insternship/admin/company-responses/${id}/verify`,
      UPLOAD_COMPANY_RESPONSE: (id: string) => `/insternship/admin/proposals/${id}/company-response`,
      HOLIDAYS: '/insternship/holidays',
    },
    INTERNSHIP_TEMPLATES: {
      GET: (name: string) => `/insternship/templates/${name}`,
      PREVIEW: (name: string) => `/insternship/templates/${name}/preview`,
      SAVE: '/insternship/templates',
    },
    INTERNSHIP_PUBLIC: {
      VERIFY_LETTER: (id: string) => `/insternship/public/verify-letter/${id}`,
    },
    METOPEN: {
      ELIGIBILITY: '/metopen/eligibility',
      TEMPLATES: '/metopen/templates',
      TEMPLATE_DETAIL: (id: string) => `/metopen/templates/${id}`,
      TEMPLATES_REORDER: '/metopen/templates/reorder',
      PUBLISH_TASKS: '/metopen/publish-tasks',
      MY_TASKS: '/metopen/my-tasks',
      TASK_DETAIL: (milestoneId: string) => `/metopen/my-tasks/${milestoneId}`,
      SUBMIT: (milestoneId: string) => `/metopen/submit/${milestoneId}`,
      MY_GATE_STATUS: '/metopen/my-gate-status',
      GRADING_QUEUE: '/metopen/grading-queue',
      GRADE: (milestoneId: string) => `/metopen/grade/${milestoneId}`,
      PROGRESS: (thesisId: string) => `/metopen/progress/${thesisId}`,
      GATE_STATUS: (thesisId: string) => `/metopen/gate-status/${thesisId}`,
      MONITORING: '/metopen/monitoring',
    },
    ASSESSMENT: {
      // TA-03A: Supervisor scoring of Metopen proposal
      SUPERVISOR_SCORING_QUEUE: '/assessment/supervisor/queue',
      SUPERVISOR_SUBMIT_SCORE: (thesisId: string) => `/assessment/supervisor/${thesisId}/score`,
      // TA-03B: Metopen lecturer scoring
      METOPEN_SCORING_QUEUE: '/assessment/metopen/queue',
      METOPEN_SUBMIT_SCORE: (thesisId: string) => `/assessment/metopen/${thesisId}/score`,
      METOPEN_PUBLISH: (thesisId: string) => `/assessment/metopen/${thesisId}/publish`,
      // Shared: Get criteria by assessment form code
      CRITERIA: (formCode: string) => `/assessment/criteria/${formCode}`,
    },
    ADVISOR_REQUEST: {
      ACCESS_STATE: '/advisorRequest/access-state',
      SUBMIT: '/advisorRequest',
      CATALOG: '/advisorRequest/catalog',
      MY_REQUESTS: '/advisorRequest/my',
      WITHDRAW: (id: string) => `/advisorRequest/${id}/withdraw`,
      LECTURER_INBOX: '/advisorRequest/inbox',
      KADEP_INBOX: '/advisorRequest/kadep-queue',
      DETAIL: (id: string) => `/advisorRequest/${id}`,
      LECTURER_DECISION: (id: string) => `/advisorRequest/${id}/respond`,
      KADEP_DECISION: (id: string) => `/advisorRequest/${id}/decide`,
      ASSIGN: (id: string) => `/advisorRequest/${id}/assign`,
    },
    QUOTA: {
      BROWSE: '/quota/browse',
      LECTURER_DETAIL: (lecturerId: string) => `/quota/browse/${lecturerId}`,
      CHECK: (lecturerId: string) => `/quota/check/${lecturerId}`,
      SCIENCE_GROUPS: '/quota/science-groups',
      TOPICS: '/quota/topics',
      DEFAULT_CONFIG: '/quota/config/default',
      LECTURER_CONFIG: (lecturerId: string) => `/quota/config/lecturer/${lecturerId}`,
      DELETE_LECTURER_CONFIG: (quotaId: string) => `/quota/config/lecturer/${quotaId}`,
      ACCEPTING_REQUESTS: '/quota/accepting-requests',
      MONITORING: '/quota/monitoring',
    },
  },
  TIMEOUT: 10000, // 10 detik
};

// Helper function untuk membuat full URL
export const getApiUrl = (endpoint: string): string => {
  return `${API_CONFIG.BASE_URL}${endpoint}`;
};
