import { ENV } from './env';

// Konfigurasi API
export const API_CONFIG = {
  BASE_URL: ENV.API_BASE_URL,
  ENDPOINTS: {
    AUTH: {
      LOGIN: '/auth/login',
      REFRESH: '/auth/refresh',
      LOGOUT: '/auth/logout',
      ME: '/auth/me',
      UPDATE_PROFILE: '/auth/profile',
      CHANGE_PASSWORD: '/auth/password',
      FORGOT_PASSWORD: '/auth/reset/request',
      RESET_PASSWORD: '/auth/reset/confirm',
      ACTIVATE_ACCOUNT: '/auth/verify/request',
      MICROSOFT_LOGIN: '/auth/microsoft/login',
      MICROSOFT_CALLBACK: '/auth/microsoft/callback',
    },
    USER: {
      PROFILE: '/user/profile',
    },
    PROFILE: {
      UPLOAD_AVATAR: '/profile/avatar',
      DELETE_AVATAR: '/profile/avatar',
      SERVE_AVATAR: (fileName: string) => `/profile/avatar/${fileName}`,
      LECTURER_DATA: '/profile/lecturer-data',
    },
    CPL: {
      BASE: '/cpl',
      BY_ID: (id: string) => `/cpl/${id}`,
      TOGGLE: (id: string) => `/cpl/${id}/toggle`,
    },
    CPMK: {
      BASE: '/cpmk',
      BY_ID: (id: string) => `/cpmk/${id}`,
      TOGGLE: (id: string) => `/cpmk/${id}/toggle`,
    },
    RUBRIC_SEMINAR: {
      CPMKS: '/rubric-seminar/cpmks',
      CRITERIA: '/rubric-seminar/criteria',
      CRITERIA_BY_ID: (criteriaId: string) => `/rubric-seminar/criteria/${criteriaId}`,
      CPMK_CONFIG: (cpmkId: string) => `/rubric-seminar/cpmk/${cpmkId}`,
      CRITERIA_RUBRICS: (criteriaId: string) => `/rubric-seminar/criteria/${criteriaId}/rubrics`,
      RUBRIC_BY_ID: (rubricId: string) => `/rubric-seminar/rubrics/${rubricId}`,
      CRITERIA_TOGGLE: (criteriaId: string) => `/rubric-seminar/criteria/${criteriaId}/toggle`,
      CRITERIA_REORDER: '/rubric-seminar/criteria/reorder',
      RUBRICS_REORDER: '/rubric-seminar/rubrics/reorder',
      WEIGHT_SUMMARY: '/rubric-seminar/weight-summary',
    },
    RUBRIC_DEFENCE: {
      CPMKS: (role: string) => `/rubric-defence/cpmks?role=${role}`,
      CRITERIA: '/rubric-defence/criteria',
      CRITERIA_BY_ID: (criteriaId: string) => `/rubric-defence/criteria/${criteriaId}`,
      CPMK_CONFIG: (cpmkId: string, role: string) => `/rubric-defence/cpmk/${cpmkId}?role=${role}`,
      CRITERIA_RUBRICS: (criteriaId: string) => `/rubric-defence/criteria/${criteriaId}/rubrics`,
      RUBRIC_BY_ID: (rubricId: string) => `/rubric-defence/rubrics/${rubricId}`,
      CRITERIA_TOGGLE: (criteriaId: string) => `/rubric-defence/criteria/${criteriaId}/toggle`,
      CRITERIA_REORDER: '/rubric-defence/criteria/reorder',
      RUBRICS_REORDER: '/rubric-defence/rubrics/reorder',
      WEIGHT_SUMMARY: (role: string) => `/rubric-defence/weight-summary?role=${role}`,
    },
    EXIT_SURVEY: {
      BASE: '/exitSurvey',
      BY_ID: (id: string) => `/exitSurvey/${id}`,
      TOGGLE: (id: string) => `/exitSurvey/${id}/toggle`,
      DUPLICATE: (id: string) => `/exitSurvey/${id}/duplicate`,
      QUESTIONS: (formId: string) => `/exitSurvey/${formId}/questions`,
      QUESTION_BY_ID: (formId: string, questionId: string) => `/exitSurvey/${formId}/questions/${questionId}`,
    },
    YUDISIUM_REQUIREMENTS: {
      BASE: '/yudisiumRequirements',
      BY_ID: (id: string) => `/yudisiumRequirements/${id}`,
      TOGGLE: (id: string) => `/yudisiumRequirements/${id}/toggle`,
      MOVE_TOP: (id: string) => `/yudisiumRequirements/${id}/move-top`,
      MOVE_BOTTOM: (id: string) => `/yudisiumRequirements/${id}/move-bottom`,
    },
    NOTIFICATION: {
      BASE: '/notification',
      UNREAD_COUNT: '/notification/unread-count',
      CHECK_THESIS_DELETED: '/notification/check-thesis-deleted',
      MARK_ALL_READ: '/notification/read-all',
      MARK_READ: (id: string) => `/notification/${id}/read`,
      DELETE: (id: string) => `/notification/${id}`,
      DELETE_ALL: '/notification/all',
      FCM_REGISTER: '/notification/fcm/register',
      FCM_UNREGISTER: '/notification/fcm/unregister',
    },
    THESIS_STUDENT: {
      BASE: '/thesisGuidance/student',
      GUIDANCE_LIST: '/thesisGuidance/student/guidance',
      GUIDANCE_DETAIL: (id: string) => `/thesisGuidance/student/guidance/${id}`,
      GUIDANCE_REQUEST: '/thesisGuidance/student/guidance/request',
      GUIDANCE_RESCHEDULE: (id: string) => `/thesisGuidance/student/guidance/${id}/reschedule`,
      GUIDANCE_CANCEL: (id: string) => `/thesisGuidance/student/guidance/${id}/cancel`,
      GUIDANCE_NOTES: (id: string) => `/thesisGuidance/student/guidance/${id}/notes`,
      PROGRESS: '/thesisGuidance/student/progress',
      PROGRESS_COMPLETE: '/thesisGuidance/student/progress/complete',
      HISTORY: '/thesisGuidance/student/history',
      SUPERVISORS: '/thesisGuidance/student/supervisors',
      SUPERVISOR_AVAILABILITY: (supervisorId: string) => `/thesisGuidance/student/supervisors/${supervisorId}/availability`,
      // Session Summary
      NEEDS_SUMMARY: '/thesisGuidance/student/needs-summary',
      SUBMIT_SUMMARY: (guidanceId: string) => `/thesisGuidance/student/guidance/${guidanceId}/submit-summary`,
      COMPLETE_SESSION: (guidanceId: string) => `/thesisGuidance/student/guidance/${guidanceId}/complete`,
      COMPLETED_HISTORY: '/thesisGuidance/student/completed-history',
      EXPORT_GUIDANCE: (guidanceId: string) => `/thesisGuidance/student/guidance/${guidanceId}/export`,
      GENERATE_LOG: '/thesisGuidance/student/guidance/generate-log',
      // My Thesis
      MY_THESIS: '/thesisGuidance/student/my-thesis',
      UPDATE_THESIS_TITLE: '/thesisGuidance/student/my-thesis/title',
      THESIS_HISTORY: '/thesisGuidance/student/thesis-history',
      PROPOSE_THESIS: '/thesisGuidance/student/propose-thesis',
      // Pembimbing 2 Request
      AVAILABLE_SUPERVISORS_2: '/thesisGuidance/student/available-supervisors-2',
      REQUEST_SUPERVISOR_2: '/thesisGuidance/student/request-supervisor-2',
      PENDING_SUPERVISOR_2: '/thesisGuidance/student/pending-supervisor-2-request',
      CANCEL_SUPERVISOR_2: '/thesisGuidance/student/cancel-supervisor-2-request',
    },
    THESIS_LECTURER: {
      BASE: '/thesisGuidance/lecturer',
      MY_STUDENTS: '/thesisGuidance/lecturer/my-students',
      MY_STUDENTS_DETAIL: (thesisId: string) => `/thesisGuidance/lecturer/my-students/${thesisId}`,
      REQUESTS: '/thesisGuidance/lecturer/requests',
      SCHEDULED: '/thesisGuidance/lecturer/scheduled',
      REQUEST_REJECT: (guidanceId: string) => `/thesisGuidance/lecturer/requests/${guidanceId}/reject`,
      REQUEST_APPROVE: (guidanceId: string) => `/thesisGuidance/lecturer/requests/${guidanceId}/approve`,
      REQUEST_CANCEL: (guidanceId: string) => `/thesisGuidance/lecturer/requests/${guidanceId}/cancel`,
      PROGRESS_SUMMARY: '/thesisGuidance/lecturer/progress',
      PROGRESS_DETAIL: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}`,
      PROGRESS_APPROVE_COMPONENTS: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}/approve`,
      PROGRESS_FINAL_APPROVAL: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}/final-approval`,
      FAIL_THESIS: (studentId: string) => `/thesisGuidance/lecturer/progress/${studentId}/fail`,
      FEEDBACK: (guidanceId: string) => `/thesisGuidance/lecturer/feedback/${guidanceId}`,
      GUIDANCE_HISTORY: (studentId: string) => `/thesisGuidance/lecturer/guidance-history/${studentId}`,
      SUPERVISOR_ELIGIBILITY: '/thesisGuidance/lecturer/supervisor/eligibility',
      // Session Summary Approval
      PENDING_APPROVAL: '/thesisGuidance/lecturer/pending-approval',
      APPROVE_SUMMARY: (guidanceId: string) => `/thesisGuidance/lecturer/guidance/${guidanceId}/approve-summary`,
      REJECT_SUMMARY: (guidanceId: string) => `/thesisGuidance/lecturer/guidance/${guidanceId}/reject-summary`,
      // Guidance Detail
      GUIDANCE_DETAIL: (guidanceId: string) => `/thesisGuidance/lecturer/guidance/${guidanceId}`,
      // Pembimbing 2 Requests
      SUPERVISOR2_REQUESTS: '/thesisGuidance/lecturer/supervisor2-requests',
      SUPERVISOR2_APPROVE: (requestId: string) => `/thesisGuidance/lecturer/supervisor2-requests/${requestId}/approve`,
      SUPERVISOR2_REJECT: (requestId: string) => `/thesisGuidance/lecturer/supervisor2-requests/${requestId}/reject`,
      APPROVE_THESIS_PROPOSAL: (thesisId: string) => `/thesisGuidance/lecturer/proposals/${thesisId}/approve`,
      TRANSFER_ELIGIBLE_LECTURERS: '/thesisGuidance/lecturer/transfer/eligible-lecturers',
      TRANSFER_REQUEST: '/thesisGuidance/lecturer/transfer/request',
      TRANSFER_INCOMING: '/thesisGuidance/lecturer/transfer/incoming',
      TRANSFER_APPROVE: (notificationId: string) => `/thesisGuidance/lecturer/transfer/${notificationId}/approve`,
      TRANSFER_REJECT: (notificationId: string) => `/thesisGuidance/lecturer/transfer/${notificationId}/reject`,
    },
    THESIS_MONITORING: {
      DASHBOARD: '/thesisGuidance/monitoring/dashboard',
      TRANSFERS_PENDING: '/thesisGuidance/monitoring/transfers/pending',
      TRANSFERS_ALL: '/thesisGuidance/monitoring/transfers/all',
      TRANSFER_APPROVE: (notificationId: string) => `/thesisGuidance/monitoring/transfers/${notificationId}/approve`,
      TRANSFER_REJECT: (notificationId: string) => `/thesisGuidance/monitoring/transfers/${notificationId}/reject`,
    },
    THESIS_SEMINAR_STUDENT: {
      OVERVIEW: '/thesisSeminar/student/overview',
      ATTENDANCE: '/thesisSeminar/student/attendance',
      DOCUMENT_TYPES: '/thesisSeminar/student/documents/types',
      DOCUMENTS: '/thesisSeminar/student/documents',
      DOCUMENT_UPLOAD: '/thesisSeminar/student/documents/upload',
      DOCUMENT_VIEW: (documentTypeId: string) => `/thesisSeminar/student/documents/${documentTypeId}`,
      ANNOUNCEMENTS: '/thesisSeminar/student/announcements',
      REGISTER_AUDIENCE: (seminarId: string) => `/thesisSeminar/student/announcements/${seminarId}/register`,
      REVISIONS: '/thesisSeminar/student/revisions',
      REVISION_SUBMIT: (revisionId: string) => `/thesisSeminar/student/revisions/${revisionId}/submit`,
      REVISION_SAVE_ACTION: (revisionId: string) => `/thesisSeminar/student/revisions/${revisionId}/action`,
      REVISION_SUBMIT_NEW: (revisionId: string) => `/thesisSeminar/student/revisions/${revisionId}/submit`,
      REVISION_CANCEL_SUBMIT: (revisionId: string) => `/thesisSeminar/student/revisions/${revisionId}/cancel-submit`,
      REVISION_DELETE: (revisionId: string) => `/thesisSeminar/student/revisions/${revisionId}`,
      HISTORY: '/thesisSeminar/student/history',
      SEMINAR_DETAIL: (seminarId: string) => `/thesisSeminar/student/seminars/${seminarId}`,
      SEMINAR_ASSESSMENT: (seminarId: string) => `/thesisSeminar/student/seminars/${seminarId}/assessment`,
    },
    THESIS_SEMINAR_ADMIN: {
      LIST: '/thesisSeminar/admin',
      DETAIL: (seminarId: string) => `/thesisSeminar/admin/${seminarId}`,
      VALIDATE_DOCUMENT: (seminarId: string, documentTypeId: string) =>
        `/thesisSeminar/admin/${seminarId}/documents/${documentTypeId}/validate`,
      SCHEDULING_DATA: (seminarId: string) => `/thesisSeminar/admin/${seminarId}/scheduling-data`,
      SET_SCHEDULE: (seminarId: string) => `/thesisSeminar/admin/${seminarId}/schedule`,
    },
    THESIS_SEMINAR_LECTURER: {
      EXAMINER_REQUESTS: '/thesisSeminar/lecturer/examiner-requests',
      SUPERVISED_STUDENTS: '/thesisSeminar/lecturer/supervised-students',
      SEMINAR_DETAIL: (seminarId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}`,
      EXAMINER_ASSESSMENT: (seminarId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/assessment`,
      FINALIZATION_DATA: (seminarId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/finalization`,
      FINALIZE_SEMINAR: (seminarId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/finalize`,
      SEMINAR_REVISIONS: (seminarId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/revisions`,
      FINALIZE_REVISIONS: (seminarId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/revisions/finalize`,
      APPROVE_REVISION: (seminarId: string, revisionId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/revisions/${revisionId}/approve`,
      UNAPPROVE_REVISION: (seminarId: string, revisionId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/revisions/${revisionId}/unapprove`,
      SEMINAR_AUDIENCES: (seminarId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/audiences`,
      APPROVE_AUDIENCE: (seminarId: string, studentId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/audiences/${studentId}/approve`,
      UNAPPROVE_AUDIENCE: (seminarId: string, studentId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/audiences/${studentId}/unapprove`,
      TOGGLE_AUDIENCE_PRESENCE: (seminarId: string, studentId: string) => `/thesisSeminar/lecturer/seminars/${seminarId}/audiences/${studentId}/presence`,
      RESPOND: (examinerId: string) => `/thesisSeminar/lecturer/seminars/${examinerId}/respond`,
      ASSIGNMENT_LIST: '/thesisSeminar/lecturer/assignment',
      ELIGIBLE_EXAMINERS: (seminarId: string) =>
        `/thesisSeminar/lecturer/assignment/${seminarId}/eligible-examiners`,
      ASSIGN_EXAMINERS: (seminarId: string) =>
        `/thesisSeminar/lecturer/assignment/${seminarId}`,
    },
    THESIS_DEFENCE_STUDENT: {
      OVERVIEW: '/thesisDefence/student/overview',
      DOCUMENT_TYPES: '/thesisDefence/student/documents/types',
      DOCUMENTS: '/thesisDefence/student/documents',
      DOCUMENT_UPLOAD: '/thesisDefence/student/documents/upload',
      REVISIONS: '/thesisDefence/student/revisions',
      HISTORY: '/thesisDefence/student/history',
      DEFENCE_DETAIL: (defenceId: string) => `/thesisDefence/student/defences/${defenceId}`,
      DEFENCE_ASSESSMENT: (defenceId: string) => `/thesisDefence/student/defences/${defenceId}/assessment`,
      DEFENCE_REVISIONS: (defenceId: string) => `/thesisDefence/student/defences/${defenceId}/revisions`,
      CREATE_REVISION: (defenceId: string) => `/thesisDefence/student/defences/${defenceId}/revisions`,
      SAVE_REVISION_ACTION: (revisionId: string) => `/thesisDefence/student/revisions/${revisionId}/action`,
      SUBMIT_REVISION_ACTION: (revisionId: string) => `/thesisDefence/student/revisions/${revisionId}/submit`,
      CANCEL_REVISION_SUBMIT: (revisionId: string) => `/thesisDefence/student/revisions/${revisionId}/cancel-submit`,
      DELETE_REVISION: (revisionId: string) => `/thesisDefence/student/revisions/${revisionId}`,
    },
    THESIS_DEFENCE_ADMIN: {
      LIST: '/thesisDefence/admin',
      DETAIL: (defenceId: string) => `/thesisDefence/admin/${defenceId}`,
      VALIDATE_DOCUMENT: (defenceId: string, documentTypeId: string) =>
        `/thesisDefence/admin/${defenceId}/documents/${documentTypeId}/validate`,
      SCHEDULING_DATA: (defenceId: string) => `/thesisDefence/admin/${defenceId}/scheduling-data`,
      SET_SCHEDULE: (defenceId: string) => `/thesisDefence/admin/${defenceId}/schedule`,
    },
    THESIS_DEFENCE_LECTURER: {
      EXAMINER_REQUESTS: '/thesisDefence/lecturer/examiner-requests',
      SUPERVISED_STUDENTS: '/thesisDefence/lecturer/supervised-students',
      DEFENCE_DETAIL: (defenceId: string) => `/thesisDefence/lecturer/defences/${defenceId}`,
      DEFENCE_ASSESSMENT: (defenceId: string) => `/thesisDefence/lecturer/defences/${defenceId}/assessment`,
      FINALIZATION_DATA: (defenceId: string) => `/thesisDefence/lecturer/defences/${defenceId}/finalization`,
      FINALIZE_DEFENCE: (defenceId: string) => `/thesisDefence/lecturer/defences/${defenceId}/finalize`,
      DEFENCE_REVISIONS: (defenceId: string) => `/thesisDefence/lecturer/defences/${defenceId}/revisions`,
      FINALIZE_REVISIONS: (defenceId: string) => `/thesisDefence/lecturer/defences/${defenceId}/revisions/finalize`,
      APPROVE_REVISION: (defenceId: string, revisionId: string) => `/thesisDefence/lecturer/defences/${defenceId}/revisions/${revisionId}/approve`,
      UNAPPROVE_REVISION: (defenceId: string, revisionId: string) => `/thesisDefence/lecturer/defences/${defenceId}/revisions/${revisionId}/unapprove`,
      RESPOND: (examinerId: string) => `/thesisDefence/lecturer/defences/${examinerId}/respond`,
      ASSIGNMENT_LIST: '/thesisDefence/lecturer/assignment',
      ELIGIBLE_EXAMINERS: (defenceId: string) =>
        `/thesisDefence/lecturer/assignment/${defenceId}/eligible-examiners`,
      ASSIGN_EXAMINERS: (defenceId: string) =>
        `/thesisDefence/lecturer/assignment/${defenceId}`,
    },
    LECTURER_AVAILABILITY: {
      BASE: '/lecturerAvailability',
      BY_ID: (id: string) => `/lecturerAvailability/${id}`,
      TOGGLE: (id: string) => `/lecturerAvailability/${id}/toggle`,
    },
    INTERNSHIP_STUDENT: {
      BASE: '/insternship/registration',
      PROPOSALS: '/insternship/registration/proposals',
      RESPOND_INVITATION: (id: string) => `/insternship/registration/proposals/${id}/respond`,
      COMPANIES: '/insternship/registration/companies',
      ELIGIBLE_STUDENTS: '/insternship/registration/eligible-students',
      SUBMIT_PROPOSAL: '/insternship/registration/submit',
      SUBMIT_COMPANY_RESPONSE: (proposalId: string) => `/insternship/registration/proposals/${proposalId}/company-response`,
      LOGBOOK: '/insternship/activity/logbook',
      UPDATE_LOGBOOK: (id: string) => `/insternship/activity/logbook/${id}`,
      UPDATE_DETAILS: '/insternship/activity/update-details',
      UPLOAD: '/documents/upload',
    },
    INTERNSHIP_SEKDEP: {
      BASE: '/insternship/sekdep',
      PROPOSALS: '/insternship/sekdep/proposals',
      PROPOSAL_DETAIL: (id: string) => `/insternship/sekdep/proposals/${id}`,
      COMPANY_STATS: '/insternship/sekdep/companies/stats',
      COMPANIES: '/insternship/sekdep/companies',
      COMPANY_DETAIL: (id: string) => `/insternship/sekdep/companies/${id}`,
      COMPANY_RESPONSES: '/insternship/sekdep/company-responses',
      VERIFY_COMPANY_RESPONSE: (id: string) => `/insternship/sekdep/company-responses/${id}/verify`,
      INTERNSHIPS: '/insternship/sekdep/internships',
      INTERNSHIPS_DETAIL: (id: string) => `/insternship/sekdep/internships/${id}`,
      LECTURERS_WORKLOAD: '/insternship/sekdep/lecturers/workload',
      LECTURERS_WORKLOAD_EXPORT: '/insternship/sekdep/lecturers/workload/export',
    },
    INTERNSHIP_KADEP: {
      BASE: '/insternship/kadep',
      COMPANY_STATS: '/insternship/kadep/companies/stats',
      COMPANIES: '/insternship/kadep/companies',
      COMPANY_DETAIL: (id: string) => `/insternship/kadep/companies/${id}`,
      PENDING_LETTERS: '/insternship/kadep/pending-letters',
      APPROVE_LETTER: '/insternship/kadep/approve-letter',
    },
    INTERNSHIP_ADMIN: {
      BASE: '/insternship/admin',
      COMPANY_STATS: '/insternship/admin/companies/stats',
      APPROVED_PROPOSALS: '/insternship/admin/proposals/approved',
      APPROVED_PROPOSAL_DETAIL: (id: string) => `/insternship/admin/proposals/${id}`,
      UPDATE_LETTER: (id: string) => `/insternship/admin/proposals/${id}/letter`,
      ASSIGNMENT_PROPOSALS: '/insternship/admin/assignment/proposals',
      ASSIGNMENT_PROPOSAL_DETAIL: (id: string) => `/insternship/admin/assignment/proposals/${id}`,
      UPDATE_ASSIGNMENT_LETTER: (id: string) => `/insternship/admin/assignment/proposals/${id}/letter`,
    },
    INTERNSHIP_TEMPLATES: {
      GET: (name: string) => `/insternship/templates/${name}`,
      PREVIEW: (name: string) => `/insternship/templates/${name}/preview`,
      SAVE: '/insternship/templates',
    },
    INTERNSHIP_PUBLIC: {
      VERIFY_LETTER: (id: string) => `/insternship/public/verify-letter/${id}`,
    },
    METOPEN: {
      ELIGIBILITY: '/metopen/eligibility',
      TEMPLATES: '/metopen/templates',
      TEMPLATE_DETAIL: (id: string) => `/metopen/templates/${id}`,
      TEMPLATES_REORDER: '/metopen/templates/reorder',
      PUBLISH_TASKS: '/metopen/publish-tasks',
      MY_TASKS: '/metopen/my-tasks',
      TASK_DETAIL: (milestoneId: string) => `/metopen/my-tasks/${milestoneId}`,
      SUBMIT: (milestoneId: string) => `/metopen/submit/${milestoneId}`,
      MY_GATE_STATUS: '/metopen/my-gate-status',
      GRADING_QUEUE: '/metopen/grading-queue',
      GRADE: (milestoneId: string) => `/metopen/grade/${milestoneId}`,
      PROGRESS: (thesisId: string) => `/metopen/progress/${thesisId}`,
      GATE_STATUS: (thesisId: string) => `/metopen/gate-status/${thesisId}`,
      MONITORING: '/metopen/monitoring',
    },
    ASSESSMENT: {
      // TA-03A: Supervisor scoring of Metopen proposal
      SUPERVISOR_SCORING_QUEUE: '/assessment/supervisor/queue',
      SUPERVISOR_SUBMIT_SCORE: (thesisId: string) => `/assessment/supervisor/${thesisId}/score`,
      // TA-03B: Metopen lecturer scoring
      METOPEN_SCORING_QUEUE: '/assessment/metopen/queue',
      METOPEN_SUBMIT_SCORE: (thesisId: string) => `/assessment/metopen/${thesisId}/score`,
      METOPEN_PUBLISH: (thesisId: string) => `/assessment/metopen/${thesisId}/publish`,
      // Shared: Get criteria by assessment form code
      CRITERIA: (formCode: string) => `/assessment/criteria/${formCode}`,
    },
    ADVISOR_REQUEST: {
      ACCESS_STATE: '/advisorRequest/access-state',
      SUBMIT: '/advisorRequest',
      CATALOG: '/advisorRequest/catalog',
      MY_REQUESTS: '/advisorRequest/my',
      WITHDRAW: (id: string) => `/advisorRequest/${id}/withdraw`,
      LECTURER_INBOX: '/advisorRequest/inbox',
      KADEP_INBOX: '/advisorRequest/kadep-queue',
      DETAIL: (id: string) => `/advisorRequest/${id}`,
      LECTURER_DECISION: (id: string) => `/advisorRequest/${id}/respond`,
      KADEP_DECISION: (id: string) => `/advisorRequest/${id}/decide`,
      ASSIGN: (id: string) => `/advisorRequest/${id}/assign`,
    },
    QUOTA: {
      BROWSE: '/quota/browse',
      LECTURER_DETAIL: (lecturerId: string) => `/quota/browse/${lecturerId}`,
      CHECK: (lecturerId: string) => `/quota/check/${lecturerId}`,
      SCIENCE_GROUPS: '/quota/science-groups',
      TOPICS: '/quota/topics',
      DEFAULT_CONFIG: '/quota/config/default',
      LECTURER_CONFIG: (lecturerId: string) => `/quota/config/lecturer/${lecturerId}`,
      DELETE_LECTURER_CONFIG: (quotaId: string) => `/quota/config/lecturer/${quotaId}`,
      ACCEPTING_REQUESTS: '/quota/accepting-requests',
      MONITORING: '/quota/monitoring',
    },
  },
  TIMEOUT: 10000, // 10 detik
};

// Helper function untuk membuat full URL
export const getApiUrl = (endpoint: string): string => {
  return `${API_CONFIG.BASE_URL}${endpoint}`;
};
